{
 "title": "SonarQube",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "projectName",
    "label": "项目",
    "query": "label_values(sonarqube_bugs, name)"
   },
   {
    "name": "id",
    "label": "ID",
    "query": "label_values(sonarqube_bugs{name=\"$projectName\"},key)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of bugs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Number of vulnerabilities",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Unit test coverage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Technical debt (days)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\"}/60/8"
    }
   ]
  },
  {
   "title": "Number of blocking questions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_blocker_violations{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Severity level problems",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_critical_violations{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Number of important issues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_major_violations{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Number of minor level questions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_minor_violations{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Prompt level question number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_info_violations{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Number of lines of code ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_ncloc{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Code smell number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Number of duplicate files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_duplicated_files{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Number of repeated blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_duplicated_blocks{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Number of repeated lines of code",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_duplicated_lines{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Number of duplicate files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_duplicated_files{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Cognitive complexity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_cognitive_complexity{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Unit test coverage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Code smell number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Number of repeated lines of code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sonarqube_duplicated_lines{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Number of lines of code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sonarqube_ncloc{name=\"$projectName\"}"
    }
   ]
  }
 ]
}